### ISSUE TITLE
XMLHttpRequest cannot load https://testserver.herokuapp.com/classes/Todo. Origin https://website.com is not allowed by Access-Control-Allow-Origin.

### ISSUE THREAD

**Issue by causeidm** [MrSlide/ParseBone#1]
Created a parse server on heroku using the parse-server button, trying to connect using parse bone from the server where the website is hosted.  if i remove the serverURL and connect back to Parse, everything works.  Trying to connect to the heroic server I get CORs errors

**Comment by MrSlide** [comment]
@causeidm You will have to be a bit more specific. What version of Parse Server are you running? Are you running ParseBone on the server or on the client?
Do you have source code that I can see?

**Comment by causeidm** [comment]
Thanks for the response, using this post: [cors_heroku_parse-server](http://stackoverflow.com/questions/35389389/how-can-i-host-my-own-parse-server-on-heroku-using-mongodb) I was able to fix the issue, it was on the parse-server side.  Something must be different with the new parse sdk that it isn't an issue. 

Now however, I am getting a 403 forbidden error on everything.  I am guessing it is something to do with the updated server no longer using a javascript key

**Comment by causeidm** [comment]
Nope, I'm an idiot, there was white space in my key, now I'm just getting 400 errors on classes, but a user can login
